train:
  epochs: 50
  batch: 8
  device: "cuda"
  patience: 5
  workers: 2
  augmentations: false  # Set true to enable custom augmentation

train_augmented:
  epochs: 80
  batch: 8
  device: "cuda"
  patience: 5
  workers: 2
  augmentations: true
  mosaic: 1.0
  mixup: 0.1
  degrees: 10.0
  translate: 0.1
  scale: 0.5
  shear: 2.0
  perspective: 0.0
  flipud: 0.5
  fliplr: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4

test:
  video_path: "data_video/dhaka_traffic.mp4"
  model_path: "models/yolov8_custom.pt"
  test_images_path: "data/test_data"
